version: "3.9"
services:
  handbrake:
    image: jlesage/handbrake
    volumes:
      - "./HandBrake/output:/output:rw"
      - "./HandBrake/watch:/watch:rw"
      - "./:/storage:ro"
      - "//docker/appdata/handbrake:/config:rw"
    ports:
      - "5800:5800"
    container_name: handbrake
