version: '3.9'
services:
  uptime-kuma:
    restart: always
    ports:
      - 3000:3001
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  uptime-kuma: 
